version: "3.9"
services:
  react:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - kokorei_node_modules:/app/node_modules # 特定のパスを独立した名前付きボリュームとして定義
    tty: true
    ports:
      - "5180:5173"
    command: yarn dev 

volumes:
  kokorei_node_modules:
